-- AlterTable
ALTER TABLE `Persons` MODIFY `photo_1` VARCHAR(191) NULL,
    MODIFY `photo_2` VARCHAR(191) NULL,
    MODIFY `photo_3` VARCHAR(191) NULL,
    MODIFY `photo_4` VARCHAR(191) NULL,
    MODIFY `photo_5` VARCHAR(191) NULL,
    MODIFY `photo_6` VARCHAR(191) NULL,
    MODIFY `photo_7` VARCHAR(191) NULL,
    MODIFY `photo_8` VARCHAR(191) NULL,
    MODIFY `photo_9` VARCHAR(191) NULL,
    MODIFY `photo_10` VARCHAR(191) NULL;
