
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import React, { useState, useEffect } from 'react';
import { cookies } from 'next/headers';


export const metadata: Metadata = {
  title: "Datapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="es">
      <body className="min-h-screen ">

      {children}


      </body>
    </html>
  );
}
