-- CreateTable
CREATE TABLE `Persona` (
    `idpersona` INTEGER NOT NULL,
    `idcuenta` INTEGER NULL,
    `apellido_paterno` VARCHAR(191) NULL,
    `apellido_materno` VARCHAR(191) NULL,
    `nombre` VARCHAR(191) NULL,
    `domicilio` VARCHAR(191) NULL,
    `exterior` VARCHAR(191) NULL,
    `interior` VARCHAR(191) NULL,
    `manzana_electoral` VARCHAR(191) NULL,
    `colonia` VARCHAR(191) NULL,
    `municipio_estado` VARCHAR(191) NULL,
    `edad` INTEGER NULL,
    `fecha_nacimiento` VARCHAR(191) NULL,
    `sexo` VARCHAR(191) NULL,
    `localidad` VARCHAR(191) NULL,
    `emision` VARCHAR(191) NULL,
    `vigencia` VARCHAR(191) NULL,
    `curp` VARCHAR(191) NULL,
    `clave_elector` VARCHAR(191) NULL,
    `seccion` VARCHAR(191) NULL,
    `estado` VARCHAR(191) NULL,
    `municipio` VARCHAR(191) NULL,
    `email` VARCHAR(191) NULL,
    `numero` VARCHAR(191) NULL,
    `facebook` VARCHAR(191) NULL,
    `twitter` VARCHAR(191) NULL,
    `numero_local` VARCHAR(191) NULL,
    `nota_1` VARCHAR(191) NULL,
    `nota_2` VARCHAR(191) NULL,
    `escolaridad` VARCHAR(191) NULL,
    `ocupacion` VARCHAR(191) NULL,
    `foto_1` VARCHAR(191) NULL,
    `foto_2` VARCHAR(191) NULL,
    `foto_3` VARCHAR(191) NULL,
    `foto_4` VARCHAR(191) NULL,
    `foto_5` VARCHAR(191) NULL,
    `foto_6` VARCHAR(191) NULL,
    `foto_7` VARCHAR(191) NULL,
    `foto_8` VARCHAR(191) NULL,
    `foto_9` VARCHAR(191) NULL,
    `foto_10` VARCHAR(191) NULL,
    `latitud` VARCHAR(191) NULL,
    `longitud` VARCHAR(191) NULL,
    `idnivel1` INTEGER NULL,
    `idnivel2` INTEGER NULL,
    `idnivel3` INTEGER NULL,
    `idnivel4` INTEGER NULL,
    `idnivel5` INTEGER NULL,
    `idnivel6` INTEGER NULL,
    `idnivel7` INTEGER NULL,
    `idnivel8` INTEGER NULL,
    `created_by` INTEGER NULL,
    `created_at` DATETIME(3) NULL,
    `updated_by` INTEGER NULL,
    `updated_at` DATETIME(3) NULL,
    `registro_en_movil` INTEGER NOT NULL DEFAULT 0,
    `activo` INTEGER NOT NULL DEFAULT 1,
    `parametro1` VARCHAR(191) NULL,
    `parametro2` VARCHAR(191) NULL,
    `parametro3` VARCHAR(191) NULL,
    `direccion` VARCHAR(191) NULL,
    `SAC` INTEGER NOT NULL DEFAULT 0,
    `credencial` INTEGER NOT NULL DEFAULT 0,
    `idpersona_lider` VARCHAR(191) NULL,
    `idvalidacion` INTEGER NULL,
    `whatsapp` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`idpersona`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
