-- AlterTable
ALTER TABLE `Users` MODIFY `name` VARCHAR(191) NULL,
    MODIFY `email` VARCHAR(191) NULL,
    MODIFY `email_verified_at` DATETIME(3) NULL,
    MODIFY `password` VARCHAR(191) NULL,
    MODIFY `remember_token` VARCHAR(191) NULL,
    MODIFY `idpersona` INTEGER NULL,
    MODIFY `idcuenta` INTEGER NULL,
    MODIFY `nivel` INTEGER NULL,
    MODIFY `super` INTEGER NULL,
    MODIFY `primer_acceso` INTEGER NULL,
    MODIFY `habilitado` INTEGER NULL,
    MODIFY `activo` INTEGER NULL,
    MODIFY `created_at` DATETIME(3) NULL,
    MODIFY `updated_at` DATETIME(3) NULL,
    MODIFY `logged_at` DATETIME(3) NULL,
    MODIFY `gratuita` INTEGER NULL,
    MODIFY `idpersona_lider` VARCHAR(191) NULL,
    MODIFY `visualizador` INTEGER NULL;
